title: 东莞平达电子
email: sales@hingtak.com
description: >- # this means to ignore newlines until "baseurl:"
  针座 端子 连接器 线束
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hingtak
github_username:  ba7lnn

show_excerpts: true

gem 'jekyll-paginate', group: :jekyll_plugins

#group :jekyll_plugins do
#  gem "jekyll-feed", "~> 0.12"
#  gem "jekyll-paginate"
#end

permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-sitemap
#  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed